### ISSUE TITLE
Install Sequalize

### ISSUE THREAD

**Issue by rafie796** [ahmadfaqih796/tutorial-api#1]
How to Install Sequalize ? @ahmadfaqih796

**Comment by rafie796** [comment]
You need to install necessary modules: express, sequelize, mysql2 and cors.
Run the command:
`npm install express sequelize mysql2 cors --save`

**Comment by ahmadfaqih796** [comment]
You need to install necessary modules: express, sequelize, mysql2 and cors.
Run the command:
`npm install express sequelize mysql2 cors --save`
